### ISSUE TITLE
TypeError: '>' not supported between instances of 'IrrationalFraction' and 'int'

### ISSUE THREAD

**Issue by limseunghyun95** [juneoh/ABLEUAlign#1]
안녕하세요
테스트를 하는 도중에 에러가 발생해서 남겨봅니다. 

![image](https://user-images.githubusercontent.com/58515197/213377095-d1b11083-757e-4351-9720-a9ce92878b9d.png)

테스트로 돌려보는 도중에 위와 같은 에러가 발생했습니다. 
nltk 에서 비교 연산에서 오류가 발생한거 같습니다.

테스트 진행한 환경은 아래와 같습니다.
Python: 3.6.15
--------------------
Package             Version
------------------- ----------
ableualign          0.1.1
certifi             2022.12.7
charset-normalizer  2.0.12
click               8.0.4
dataclasses         0.8
idna                3.4
importlib-metadata  4.8.3
importlib-resources 5.4.0
joblib              1.1.1
nltk                3.6.7
numpy               1.19.5
pip                 18.1
regex               2022.10.31
requests            2.27.1
setuptools          40.6.2
torch               1.10.2
torchtext           0.11.2
tqdm                4.64.1
typing-extensions   4.1.1
urllib3             1.26.14
zipp                3.6.0

감사합니다.

**Comment by juneoh** [comment]
안녕하세요!

오래 전 코드인지라 저도 가물가물 하지만.. 다시 보니 nltk를 패치하는 부분이 있는데, 제가 requirements.txt에 nltk 버전을 고정해두지 않아 이후 변경사항으로 인해 망가진 것 같습니다. nltk PyPI에서 제 커밋 날짜를 보면 nltk==3.3 정도였을 것 같은데, 한번 해보시겠어요?

**Comment by limseunghyun95** [comment]
알려주신대로 테스트 했을 때 정상적으로 동작하는 것을 확인했습니다.! 

python3.6 버전에 nltk 3.3 이면 정상 작동하는 것 같습니다.
